[package]
name = "sphincs_btc"
version = "0.1.0"
edition = "2024_07"

[lib]

[executable]

[dependencies]
cairo_execute = "2.11.4"

[dev-dependencies]
cairo_test = "2.11.4"

[features]
default = ["blake_hash"]
blake_hash = []
debug = []
