[package]
name = "sphincs_poseidon"
version = "0.1.0"
edition = "2024_07"

[lib]

[executable]

[dependencies]
cairo_execute = "2.11.4"
sphincs_plus = { path = "../sphincs-plus" }

[dev-dependencies]
cairo_test = "2.11.4"